property_positive:
  name: 'Filter 1'
  category: 'Vakances'
  sub_categories:
    - sub_category:
      title: 'Vakances'
      option: 'Aģents'
  parameters:
    - parameter:
      name: 'NOSAUKUMS'
      left: 'Smits'